Django-天天生鲜商城/cart/urls.py
from django.urls import path

from cart.views import add_cart, cart, change_session_goods, change_del_goods, is_select

urlpatterns = [
    path('cart/', cart, name='cart'),
    # 添加
    path('add_cart/', add_cart, name='add_cart'),
    # 修改数量
    path('change_session_goods/', change_session_goods, name='change_session_goods'),
    # 删除
    path('change_del_goods/', change_del_goods, name='change_del_goods'),
    # 修改选中状态
    path('is_select/', is_select, name='is_select'),

]

Django-天天生鲜商城/goods/urls.py
from django.urls import path, re_path

from goods.views import goods_detail, list

urlpatterns = [
    # 商品详情页
    path('goods_detail/<int:id>/', goods_detail, name='goods_detail'),
    # 商品列表和搜索
    re_path(r'list/(?P<sort>\d+)/(?P<type>.*)/(?P<page>\d+)/', list, name='list'),

]

Django-天天生鲜商城/order/urls.py
from django.urls import path, re_path

from order.views import place_order, user_center_order, user_center_site, user_center_info, user_center_site_alter, \
    user_change_password, center

urlpatterns = [
    # 创建订单
    re_path('^place_order/', place_order, name='place_order'),
    # 用户中心
    path('user_center_info/', user_center_info, name='user_center_info'),
    # 我的订单
    path('user_center_order/', user_center_order, name='user_center_order'),
    # 收获地址
    path('user_center_site/', user_center_site, name='user_center_site'),
    # 修改 删除地址
    path('user_center_site_alter/<int:id>', user_center_site_alter, name='user_center_site_alter'),
    path('center/', center, name='center'),
    # 修改密码
    path('user_change_password/', user_change_password, name='user_change_password')
]

Django-天天生鲜商城/tinatian/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from tinatian import settings


urlpatterns = [
    # 后台路由
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='users')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    path('cart/', include(('cart.urls', 'goods'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# handler404 = utils.

Django-天天生鲜商城/user/urls.py
from django.urls import path, re_path

from user.views import index, register, login, is_login, logout

urlpatterns = [

    # 主页
    path('index/', index, name='index'),
    # 注册
    path('register/', register, name='register'),
    # 登录
    path('login/', login, name='login'),
    # 继承页面需要获取的信息
    path('is_login/', is_login, name='is_login'),
    # 退出登录
    path('logout/', logout, name='logout'),

]

Django-天天生鲜商城/cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class Cart(models.Model):

    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=0)

    class Meta:
        db_table = 'f_cart'

Django-天天生鲜商城/goods/models.py
from django.contrib.auth.models import User
from django.db import models




class GoodsCategory(models.Model):

    CATEGORY_TYPE = (
        (1, '新鲜水果'),
        (2, '海鲜水产'),
        (3, '猪牛羊肉'),
        (4, '禽类蛋品'),
        (5, '新鲜蔬菜'),
        (6, '速冻食品'),
    )
    category_type = models.IntegerField(choices=CATEGORY_TYPE, verbose_name='类目级别')
    category_front_image = models.ImageField(upload_to='staric/web/images/', null=True, blank=True, verbose_name='封面图')

    class Meta:
        db_table = 'f_goods_category'


class Goods(models.Model):

    category = models.ForeignKey(GoodsCategory, verbose_name='商品类目', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='商品名')
    goods_sn = models.CharField(max_length=50, default='', verbose_name='商品唯一货号')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    sold_nums = models.IntegerField(default=0, verbose_name='销售量')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    goods_nums = models.IntegerField(default=0, verbose_name='商品库存')
    market_price = models.FloatField(default=0, verbose_name='市场价格')
    shop_price = models.FloatField(default=0, verbose_name='本店价格')
    goods_brief = models.CharField(max_length=500, verbose_name='商品简短描述')
    goods_desc = models.TextField(null=True)
    ship_free = models.BooleanField(default=True, verbose_name='是否承担运费')
    goods_front_image = models.ImageField(upload_to='goods/images/', null=True, blank=True, verbose_name='封面图')
    is_new = models.BooleanField(default=False, verbose_name='是否新品')
    is_hot = models.BooleanField(default=False, verbose_name='是否热销')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'f_goods'


class GoodsImage(models.Model):

    goods = models.ForeignKey(Goods, related_name='images', verbose_name='商品', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='goods/images', verbose_name='图片', null=True, blank=True)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'f_goods_images'


class Click(models.Model):
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods_id = models.ForeignKey(Goods, verbose_name='商品id', on_delete=models.CASCADE)
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'f_goods_click'

Django-天天生鲜商城/cart/views.py
from django.contrib.auth.models import User
from django.forms import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render

from goods.models import Goods
from cart.models import Cart
from user.models import UserToken


# 添加商品到购物车中
def add_cart(request):
    if request.method == 'POST':
        # 获取商品的ID个数
        goods_id = str(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))

        # 格式化 {'商品id', 商品数量}
        goods_dicr = {str(goods_id): int(goods_num)}

        # 购物车图标数量
        cart_goods_num = 0

        # 是否登录了，获取用户
        token = request.COOKIES.get('token')
        user = UserToken.objects.filter(token=token).first()

        # 已登录，添加进数据库
        if user:
            shop_carts = Cart()
            goods = Goods.objects.filter(id=goods_id).first()

            # 获取购物车数据库内的id 和数量
            shop_cart = Cart.objects.filter(user=user.user).all()
            shop_carts_nums = {str(g.goods_id): int(g.nums) for g in shop_cart}

            # 如果存在则则修改数量
            if goods_id in shop_carts_nums:
                for k, v in shop_carts_nums.items():
                    if k == goods_id:
                        carts = Cart.objects.filter(goods_id=goods_id).first()
                        carts.nums = int(v) + int(goods_num)
                        carts.save()
            # 不存在则创建
            else:
                shop_carts.nums = goods_num
                shop_carts.goods = goods
                shop_carts.user = User.objects.filter(username=user.username).first()
                shop_carts.save()

                cart_goods_num += 1


        # 没登录
        else:
            # 有session
            try:
                # 是否添加过该商品，如果没有session会报错执行except
                session = dict(request.session.get('goods'))

                # 有session 商品也以存在 {'商品id', 商品数量}
                if goods_id in session:
                    session[goods_id] += goods_num
                    request.session['goods'] = session

                # 有session 商品不存在
                else:
                    session.update(goods_dicr)
                    request.session['goods'] = session


            # 没有session
            except:
                request.session['goods'] = goods_dicr

            # 购物车商品数量，转字典 获取value sum求和
            cart_goods_num = sum([int(v) for k, v in dict(request.session['goods']).items()])

        return JsonResponse({'code': 200, 'cart_goods_num': cart_goods_num})


# 购物车
def cart(request):
    if request.method == 'GET':
        # 获取登录用户
        token = request.COOKIES.get('token')
        user = UserToken.objects.filter(token=token).first()

        # 有登录
        if user:
            # 购物车是否有商品
            try:
                # 获取购物车里商品id和数量，没商品会报错
                shop_cart = Cart.objects.filter(user=user.user).order_by('-add_time').all()
                shop_carts_nums = [[int(g.goods_id), int(g.nums)] for g in shop_cart]

                shop_carts_id = [g.goods_id for g in shop_cart]

                carts = []
                # 遍历商品id
                for id in shop_carts_id:
                    goods = Goods.objects.get(id=id)
                    good_dict = dict(model_to_dict(goods))
                    # 给商品详情表添加数量
                    for num in shop_carts_nums:
                        if good_dict['id'] == num[0]:
                            good_dict['num'] = num[1]

                    carts.append(good_dict)

            # 购物车没商品
            except:
                carts = []

            return render(request, 'web/cart.html', {'carts': carts})

        # 未登录
        if not user:
            try:
                # 从session中拿商品的id，获取不到会报错
                goods = dict(request.session.get('goods'))

                carts = []

                # 转字典添加内容
                for id, num in goods.items():
                    goods = Goods.objects.get(id=id)
                    good_dict = dict(model_to_dict(goods))

                    # 给商品详情添加 数量字段
                    good_dict['num'] = num

                    carts.append(good_dict)
            except:
                # 未加入购物车直接访问购物车返回空列表
                carts = []

            return render(request, 'web/cart.html', {'carts': carts})


# 修改购物车中数据
def change_session_goods(request):
    if request.method == 'POST':
        # 获取用户
        token = request.COOKIES.get('token')
        user = UserToken.objects.filter(token=token).first()

        # 获取商品的ID个数
        goods_id = request.POST.get('goods_id')
        goods_num = request.POST.get('goods_num')

        if user:
            # 获取购物车数据库内的id 和数量
            shop_cart = Cart.objects.filter(user_id=user.user_id).all()
            shop_carts_nums = {str(g.goods_id): int(g.nums) for g in shop_cart}

            # 如果存在则则修改数量
            if goods_id in shop_carts_nums:
                for k, v in shop_carts_nums.items():
                    if k == goods_id:
                        carts = Cart.objects.filter(goods_id=goods_id).first()
                        carts.nums = int(goods_num)
                        carts.save()
            return JsonResponse({'code': 200})

        # 没登录
        else:
            goods_session = dict(request.session.get('goods'))

            goods_nums = Goods.objects.get(id=goods_id)

            if int(goods_num) > int(goods_nums.goods_nums):
                return JsonResponse({'code': 301, 'error': '商品库存不足'})

            # 上面转字典后增加一个数量key
            goods_session[goods_id] = goods_num

            request.session['goods'] = goods_session

        return JsonResponse({'code': 200, 'goods': request.session['goods']})


# 删除数据库信息
def change_del_goods(request):
    if request.method == 'POST':
        good_id = request.POST.get('good_id')
        try:
            # 获取登录用户，不报错就是登录了
            token = request.COOKIES.get('token')
            user = UserToken.objects.filter(token=token).first().user
            try:
                Cart.objects.filter(user_id=user.user_id,goods_id=good_id).delete()
                return JsonResponse({'code': 200, 'msg': '删除成功'})
            except:
                return JsonResponse({'code': 301, 'msg': '商品不存在'})
        except:
            # 没登陆，获取session
            goods = dict(request.session.get('goods'))

            # 删除商品
            goods.pop(good_id)

            request.session['goods'] = goods

            return JsonResponse({'code': 200, 'msg': '请求成功，'})


# 修改购物车商品选中状态，准备创建订单
def is_select(request):
    if request.method == 'POST':
        try:
            # 获取用户
            token = request.COOKIES.get('token')
            user = UserToken.objects.filter(token=token).first().user

            # 转换为列表
            goods_list = eval(request.POST.get('goods_list_str'))

            # 初始化选中状态
            Cart.objects.filter(user=user).update(is_select=0)

            # 过滤 全部修改
            Cart.objects.filter(goods_id__in=goods_list).update(is_select=1)

        except:
            return JsonResponse({'code': 301, 'msg': '商品不存在'})

    return JsonResponse({'code': 200, 'msg': '请求成功'})

Django-天天生鲜商城/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="/media/goods/images/favicon.ico" type="image/x-icon" />
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>
        {% block ticle %}
        {% endblock %}
    </title>
    {% block extCss %}
    {% endblock %}

    {% block extJs %}
    {% endblock %}

    {% block extJs2 %}
    {% endblock %}


</head>
    <body>

        {% block header %}
        {% endblock %}

        {% block content %}
        {% endblock %}

        {% block footer %}
        {% endblock %}
    </body>
</html>

Django-天天生鲜商城/templates/web/base_main.html
{% extends 'web/base.html' %}

{% block extCss %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/main.css' %}">
{% endblock %}

{% block extJs %}
    {% load static %}
    <script type="text/javascript" src="{% static 'web/js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">

        {#获取用户 购物车商品数量 删除登录注册div#}
        $.getJSON('/user/is_login/', function (data) {
            if (data.code == 200) {
                $('.login_info').css('display', 'block');
                $('.login_info em').html(data.user);
                $('.goods_count').html(data.goods_count);
                $('.total_count em').html(data.goods_count);
                $('.login_btn').remove();

            } else {
                {#获取用户失败，显示提示 购物车数量#}
                $('.goods_count').html(data.goods_count);
                $('.fixed').css({"display": "inline"})
            }

        });

        function dianji() {
            var search = $('.input_text').val()
            window.location.href='/goods/list/0/'+search+'/1/'
        }
    </script>
{% endblock %}

{% block header %}
    {% load static %}
        {% csrf_token %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fixed" style="display:none;border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;
            height: 30px;background: #233;color: white;opacity: 0.4;position: fixed;top: 0;left: 40%;
            text-align: center;line-height: 30px;">&nbsp;&nbsp;当前未登录，数据将保存本地，登录后可上传。</div>

            <div class="fr">
                <div class="login_info fl" style="display:none;">
                    欢迎您：<em></em>
                    <span>&nbsp;&nbsp;&nbsp;</span>
                    <a href="{% url 'user:logout' %}" onClick="if(!confirm('是否确认退出？'))return false; ">退出登录</a>
                    <span> </span>
                    <span> </span>
                </div>
                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'order:user_center_info' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'order:user_center_order' %}">我的订单</a>

                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="{% url 'user:index' %}" class="logo fl"><img src="{% static 'web/images/logo.png' %}"></a>
        <div class="search_con fl">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品" value="{% if search %}{{ search }}{% endif %}">
            <input type="button" class="input_btn fr" name="" onclick="dianji()" value="搜索">
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl cart_goods_num" id="show_count"></div>
        </div>
    </div>


{% endblock %}

{% block footer %}
    <div class="footer no-mp">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
{% endblock %}

Django-天天生鲜商城/templates/web/detail.html
{% extends  'web/base_main.html' %}

{% block ticle %}
    天天生鲜-商品详情
{% endblock %}

{% block content %}
    {% load static %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
				<ul class="subnav">
					<li><a href="{% url 'goods:list' 0 1 1 %}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' 0 2 1 %}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' 0 3 1 %}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' 0 4 1 %}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' 0 5 1 %}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' 0 6 1 %}" class="ice">速冻食品</a></li>
				</ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'user:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="{% url 'goods:list' 0 0 1 %}">全部商品</a></li>
				<li class="interval">|</li>
				<li><a href=""></a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' 0 goods.category_id 1 %}">
            {{ goods.category.get_category_type_display }}
        </a>
        <span>></span>
        {{ goods.name }}
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ goods.goods_front_image }}" width="100%" height="100%"></div>

        <div class="goods_detail_list fr">
            <h3>{{ goods.name }}</h3>
            <p>{{ goods.goods_brief }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ goods.shop_price }}</em></span>
                <span class="show_unit">单  位：{{ goods.market_price }}g</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>

                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1" onblur="change_goods({{ goods.shop_price }},parseInt($('.num_show').val()))">
                    <a href="javascript:;" class="add fr" onclick="add_goods({{ goods.shop_price }});">+</a>
                    <a href="javascript:;" class="minus fr" onclick="sub_goods({{ goods.shop_price }});">-</a>
                </div>
                {#库存#}
                <input id="ku" style="display:none;" value="{{ goods.goods_names }}">

                <div class="popup_con">
                    <div class="popup">
                        <p>加入购物车成功！</p>
                    </div>
                    <div class="mask"></div>
                </div>

                <div class="num_name fl" style="margin-left:50px;">库 存：</div>
                <div class="num_name fl" style="text-align:center;">
                    {{ goods.goods_nums }}
                </div>
            </div>
            <div class="total">总价：<em>{{ goods.shop_price }}元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn" onclick="at_once({{ goods.id }})">立即购买</a>
                {% csrf_token %}
                <a onclick="add_cart({{ goods.id }});" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for goods in goods_new %}
					<li>
						<a href="/goods/goods_detail/{{ goods.id }}/"><img src="{{ goods.goods_front_image }}"></a>
						<h4><a href="/goods/goods_detail/{{ goods.id }}/">{{ goods.name }}</a></h4>
						<div class="prize">￥{{ goods.shop_price }}</div>
					</li>
					{% endfor %}
				</ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ goods.goods_desc }}</dd>
                </dl>
            </div>

        </div>
    </div>

    <script type="text/javascript">

        {#商品数量增加#}
        function add_goods(price) {
            var kucun = parseInt($('.num_name').eq(2).text());
            var goods_num = parseInt($('.num_show').val());
            {#计算总价#}
            if (goods_num < kucun) {
                $('.num_show').val(goods_num + 1);
                var total_price = (goods_num + 1) * price;
                $('.total em').html(total_price.toFixed(1) + '元')
            }
        }

        {#商品减少#}
        function sub_goods(price) {
            var goods_num = $('.num_show').val();

            if (goods_num > 1) {
                $('.num_show').val(goods_num - 1);
                var total_price = (goods_num - 1) * price;
                $('.total em').html(total_price.toFixed(1) + '元')
            }
        }

        {#直接修改input框里的数量#}
        function change_goods(price,num) {
            var goods_num = $('.num_show').val();
            {#计算总价#}
            $('.num_show').val(num);
            var total_price = num * price;
            $('.total em').html(total_price.toFixed(1) + '元')
        }

        {#添加购物车#}
        function add_cart(goods_id) {

            goods_num = $('.num_show').val();
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url: '/cart/add_cart/',
                type: 'POST',
                data: {'goods_id': goods_id, 'goods_num': goods_num},
                dataType: 'json',
                headers: {'X-CSRFToken': csrf},
                success: function (data) {
                    if (data.code == 200) {
                        {#获取现页面数量动态增加#}
                        num = parseInt($('#show_count').text())+parseInt(goods_num);
                        $('#show_count').html(num);

                        {#加入购物车成功弹窗#}
                        $('.popup_con').fadeIn('fast', function() {

                            setTimeout(function(){
                                $('.popup_con').fadeOut('fast',function(){
                                });
                            },500)

                        });
                    }
                }
            });


        }


        {#  立即购买（加入购物车版）#}
        {#function at_once(goods_id) {#}
        {##}
        {#  先加入购物车，成功后跳转购物车界面#}
        {#    add_cart(goods_id);#}
        {##}
        {#    csrf = $('input[name="csrfmiddlewaretoken"]').val();#}
        {#    goods_id_str = '['+goods_id+']';#}
        {##}
        {#    $.ajax({#}
        {#        url: '/cart/is_select/',#}
        {#        type: 'POST',#}
        {#        data: {'goods_list_str': goods_id_str},#}
        {#        datatype: 'json',#}
        {#        headers: {'X-CSRFToken': csrf},#}
        {#        success: function (data) {#}
        {#            if (data.code == 200) {#}
        {#                window.location.href = '/cart/cart/'#}
        {#            }#}
        {#        }#}
        {##}
        {##}
        {#    })#}
        {# }#}

        {#立即购买，跳转结算#}
        function at_once(goods_id) {
            $.getJSON('/user/is_login/', function (data) {
                if (data.code == 200) {
                    var goods_num = $('.num_show').val();
                    window.location.href = '/order/place_order/?goods_id='+goods_id+'&goods_num='+goods_num
                }else {
                    window.location.href = '/user/login/'
                }
            })
        }


    </script>
{% endblock %}

Django-天天生鲜商城/templates/web/index.html
{% extends  'web/base_main.html' %}

{% block ticle %}
    天天生鲜-首页
{% endblock %}

{% block extJs %}
    {{ block.super }}
    {% load static %}
	<script type="text/javascript" src="{% static 'web/js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'web/js/slide.js' %}"></script>

{% endblock %}


{% block content %}
    {% load static %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'user:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="{% url 'goods:list' 0 0 1%}">全部商品</a></li>
				<li class="interval">|</li>
				<li><a href=""></a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            <li><a href="{% url 'goods:list' 0 1 1 %}" class="fruit">新鲜水果</a></li>
            <li><a href="{% url 'goods:list' 0 2 1 %}" class="seafood">海鲜水产</a></li>
            <li><a href="{% url 'goods:list' 0 3 1 %}" class="meet">猪牛羊肉</a></li>
            <li><a href="{% url 'goods:list' 0 4 1 %}" class="egg">禽类蛋品</a></li>
            <li><a href="{% url 'goods:list' 0 5 1 %}" class="vegetables">新鲜蔬菜</a></li>
            <li><a href="{% url 'goods:list' 0 6 1 %}" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'web/images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'web/images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'web/images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'web/images/slide04.jpg' %}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'web/images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'web/images/adv02.jpg' %}"></a>
		</div>
	</div>

    {% for k, type in goodstype.items %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ type.2.category_type }}">
                    {{ type.2.get_category_type_display }}
                </h3>
                <div class="subtitle fl">
                    <span>|</span>

                    {% for i in type.1 %}
                        {# 限制显示单个长度#}
                        <a href="{% url 'goods:goods_detail' i.id %}" class="goods_more">{{ i.name|slice:'5' }}</a>
                    {% endfor %}
                </div>
                <a href="{% url 'goods:list' 0 type.2.category_type 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl">
                    <a href="{% url 'goods:list' 0 type.2.category_type 1 %}">
                        <img src="{{ type.2.category_front_image }}">
                    </a>
                </div>
                <ul class="goods_list fl ">
                    {% for good in type.0 %}
                        <li>
                            <h4><a href="">{{ good.name }}</a></h4>
                            <a href="{% url 'goods:goods_detail' good.id %}"><img src="{{ good.goods_front_image }}"></a>
                            <div class="prize">¥ {{ good.shop_price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

{% endblock %}