Flask-个人博客/myblog/models/post.py
from functools import partial
from datetime import datetime

from utils import markdown2html
from . import db, Mixin
from .tag import TagModel, create_tag, get_tag_byname, tags_diff, delete_tag_nopost


class PostModel(db.Model, Mixin):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Unicode(128), nullable=False)  # 标题
    summary_html = db.Column(db.UnicodeText)            # 概述
    maintext_html = db.Column(db.UnicodeText)           # 正文
    raw_markdown = db.Column(db.UnicodeText)            # 原始markdown

    temporary = db.Column(db.Boolean, default=True)     # 临时的

    posted_at = db.Column(db.DateTime, default=datetime.now())    # 发表于...
    updated_at = db.Column(db.DateTime, default=datetime.now())   # 更新于...


def parse_markdown_post(markdown_file):
    title, tags, maintext, summary = '', '', [], []
    over_summary = False
    for line in markdown_file.readlines():
        line = line.decode()
        if tags and title:
            maintext.append(line)
            if over_summary is not True:
                summary.append(line)
        if line.startswith('tags:'):
            tags = line[len('tags:'):].strip()
        elif line.startswith('title:'):
            title = line[len('title:'):].strip()
        elif line.startswith('#'):
            over_summary = True
    # 去空
    tags = [t for t in tags.split(' ') if len(t)]
    summary = ''.join(summary[:-1])
    maintext = ''.join(maintext)
    return title, tags, summary, maintext


def create_post(markdown_file):
    title, tags, md_summary, md_maintext = parse_markdown_post(markdown_file)
    new_tags, repeated_tags = tags_diff(tags)

    tags = []
    tags.extend([create_tag(tagname) for tagname in new_tags])
    tags.extend([get_tag_byname(tagname) for tagname in repeated_tags])

    post = PostModel(
        title=title,
        summary_html=markdown2html(md_summary),
        maintext_html=markdown2html(md_maintext),
        raw_markdown=md_maintext,
        tags=tags
    )
    return post.save()


def get_post(post_id: int):
    return PostModel.query.get(post_id)


def get_post_bytitle(post_title):
    return PostModel.query.filter_by(title=post_title).first()


def get_posts(desc=False):
    if desc:
        return PostModel.query.order_by(PostModel.posted_at.desc()).all()
    else:
        return PostModel.query.all()


def replace_post(src_post, dist_post):
    dist_post.title = src_post.title
    dist_post.summary_html = src_post.summary_html
    dist_post.maintext_html = src_post.maintext_html
    dist_post.raw_markdown = src_post.raw_markdown
    dist_post.tags = src_post.tags
    dist_post.updated_at = datetime.now()

    delete_post(src_post)


def delete_post(post):
    post.delete()
    post.commit()
    delete_tag_nopost()

Flask-个人博客/myblog/app/main/__init__.py
from flask import Blueprint

blueprint = Blueprint('main', __name__)

from . import views

Flask-个人博客/myblog/app/main/views.py
from flask import render_template, g, request

from . import blueprint
from models.post import get_post, get_post_bytitle, get_posts
from models.tag import TagModel, get_tag_byname
from models.user import UserModel


@blueprint.route('/test')
def test():
    return render_template('main/test.html')


@blueprint.route('/')
def index():
    user = UserModel.query.get(1)
    _posts = get_posts(desc=True)
    tags = TagModel.query.all()
    return render_template('main/index.html', posts=_posts, tags=tags, user=user)


@blueprint.route('/post/<int:post_id>')
def post(post_id):
    _post = get_post(post_id)
    return render_template('main/post.html', post=_post)


@blueprint.route('/post')
def posts():
    tag_name = request.args.get('tag', '', str)
    if tag_name is not None:
        tag = get_tag_byname(tag_name)
        _posts = tag.posts
    else:
        _posts = get_posts()
    return render_template('main/posts.html', tag_name=tag_name, posts=_posts)


@blueprint.route('/resume')
def resume():
    return render_template('main/resume.html', post=get_post_bytitle('个人简历'))

Flask-个人博客/myblog/app/templates/main/_footer.html
<footer class="d-flex w-100 justify-content-center" style="margin: 80px auto;">
  &copy;2018 fushall
</footer>

Flask-个人博客/myblog/app/templates/main/_header.html
<header class="navbar navbar-expand-lg navbar-light bg-light mb-3 w-100 justify-content-center">
  <div style="width: 970px;">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">兴小院</a>
  </div>
</header>

Flask-个人博客/myblog/app/templates/main/index.html
{% extends 'layout/bootstrap.html' %}


{% block title %}
  blog - 兴小院
{% endblock %}

{% block header %}
  {% include 'main/_header.html' %}
{% endblock %}


{% block content %}
  <div class="container d-flex justify-content-between" style="width: 1000px;">
    {# sidebar #}
    <div style="width: 380px;">
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div>基本信息</div>
          <a href="{{ url_for('main.resume') }}">简历</a>
        </div>
        <div class="card-body">
         {{ user.info_html|safe }}
        </div>
      </div>

      <div class="card mt-3">
        <div class="card-header">标签</div>
        <div class="card-body  flex-wrap">
          {% for tag in tags %}
            <a class="btn btn-info btn-sm mb-1" href="{{ url_for('main.posts', tag=tag.name) }}">
              {{ tag.name }}<span class="badge badge-light ml-1">{{ tag.posts.__len__() }}</span>
            </a>
          {% endfor %}
        </div>
      </div>

    </div>

    {# content #}
    <div class="ml-3 w-100">
      <div class="card">
        <div class="card-header">文章列表</div>
        <div class="card-body">
          <ul class="list-group">
            {% for post in posts %}
              {% if not post.temporary %}
                <li class="list-group-item">
                  <a href="{{ url_for('main.post', post_id=post.id) }}"><h5>{{ post.title }}</h5></a>
                  <div class="mb-3">更新于：{{ post.updated_at }}</div>
                  <p style="color: gray;">{{ post.summary_html|safe }}</p>
                </li>
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}


{% block footer %}
  {% include 'main/_footer.html' %}
{% endblock %}

Flask-个人博客/myblog/app/templates/main/post.html
{% extends 'layout/bootstrap.html' %}


{% block title %}
  {{ post.title }} - 兴小院
{% endblock %}


{% block content %}

  <div class="container d-flex flex-column" style="margin: 60px auto 0 auto;max-width: 1000px;">
    {# header #}

    {# content #}
    <div class="d-flex">

      {# post #}
      <div style="min-width: 650px">

        <h1>{{ post.title }}</h1>
        <div class="mb-1">发表于：{{ post.posted_at }}</div>
        <div class="mb-3">更新于：{{ post.posted_at }}</div>
        <div>{{ post.maintext_html|safe }}</div>

      </div>
    </div>
      <footer class="mt-5 text-center mb-2" style="color: #8590a6; font-size: small;">© 2018 fushall</footer>
  </div>
{% endblock content %}

Flask-个人博客/myblog/app/templates/main/posts.html
{% extends 'layout/bootstrap.html' %}


{% block title %}
  博客文章 - 兴小院
{% endblock %}

{% block header %}
  {% include 'main/_header.html' %}
{% endblock %}


{% block content %}
  <div class="container d-flex justify-content-between" style="width: 1000px;">
    <div style="width: 960px">
      <div class="card">
        <div class="card-header">标签：{{ tag_name }}</div>
        <div class="card-body">
          <ul class="list-group">
            {% for post in posts %}
              <li class="list-group-item">
                <a href="{{ url_for('main.post', post_id=post.id) }}">
                  <h5>{{ post.title }}</h5>
                </a>
                <div class="mb-3">更新于：{{ post.updated_at }}</div>
                <p style="color: gray;">{{ post.summary_html|safe }}</p>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}


{% block footer %}
  {% include 'main/_footer.html' %}
{% endblock %}

Flask-个人博客/myblog/app/templates/main/resume.html
{% extends 'layout/bootstrap.html' %}


{% block title %}
  个人简历
{% endblock %}


{% block content %}

  <div class="container d-flex flex-column" style="margin: 30px auto 0 auto;max-width: 1000px;">
    {# header #}

    {# content #}
    <div class="d-flex">

      {# post #}
      <div style="min-width: 650px">

        <h1>{{ post.title }}</h1>
        <div class="mb-3">更新于：{{ post.posted_at }}</div>
        <div>{{ post.maintext_html|safe }}</div>

      </div>
    </div>
  </div>
{% endblock content %}

{% block myscripts %}
  <script>
    $('table').attr('class', 'table table-bordered');
    console.log($('table'));
  </script>
{% endblock %}

{% block mystyles %}
  <style>
    h1, h2, h3, h4, h5, h6 {
      font-weight: 500;
    }

    h2 {
      margin: 25px 0 20px;
      font-size: 26px;
    }

    ul, ol {
      padding: 0;
      margin: 0 0 10px 25px;
    }
  </style>
{% endblock %}

Flask-个人博客/myblog/app/templates/main/test.html
{% extends 'layout/bootstrap.html' %}

{% block title %}测试代码的页面{% endblock %}


{% block content %}
  <div class="container justify-content-center">
    <div id="div" class="border" style="width: 360px; height: 240px;">
      <p class="border mt-3">标签1</p>
      <p class="border">标签2</p>
      <p class="border">标签3</p>
    </div>
    <button id="btn1">？？？</button>
  </div>
{% endblock %}

{% block myscripts %}
  <script>
    var div = document.getElementById('div');
    var p = document.querySelectorAll('p');
    console.log(p);

  </script>
{% endblock %}